name: buggy-todo
services:
  - name: api
    github:
      repo: DO-Solutions/buggy-todo
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    source_dir: /
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
